export enum ChapterStatus {
  DRAFT = "DRAFT",
  IN_PROGRESS = "IN_PROGRESS",
  READY_FOR_EDITOR_REVIEW = "READY_FOR_EDITOR_REVIEW",
  EDITOR_APPROVED = "EDITOR_APPROVED",
  PUBLISHED = "PUBLISHED",
}
