export enum NotificationType {
  DEADLINE = "DEADLINE",
  TASK_ASSIGNMENT = "TASK_ASSIGNMENT",
  SUBMISSION = "SUBMISSION",
  REVISION = "REVISION",
  REVIEW = "REVIEW",
  PROPOSAL_DECISION = "PROPOSAL_DECISION",
  RISK_ALERT = "RISK_ALERT",
  DECISION = "DECISION",
  DISPUTE = "DISPUTE",
  GENERAL = "GENERAL",
}
